# Generated by Django 2.2.17 on 2021-03-21 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210321_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='langs',
            field=models.CharField(blank=True, max_length=512, verbose_name='языки'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_profile_url',
            field=models.CharField(blank=True, max_length=128, verbose_name='ссылка на профиль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 12, 8, 52, 75095, tzinfo=utc)),
        ),
    ]
