USE vk;
-- Задание 2: создаем таблицу постов и лайков (в начале сделаю её, чтобы потом расставить внешние ключи сразу везде)
DROP TABLE IF EXISTS likes;
CREATE TABLE likes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  target_id INT UNSIGNED NOT NULL,
  target_type_id INT UNSIGNED NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS target_types;
CREATE TABLE target_types (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO target_types (name) VALUES 
  ('messages'),
  ('users'),
  ('media'),
  ('posts');
  
INSERT INTO likes -- Заполняем лайки
  SELECT 
    id, 
    FLOOR(1 + (RAND() * 100)), 
    FLOOR(1 + (RAND() * 100)),
    FLOOR(1 + (RAND() * 4)),
    CURRENT_TIMESTAMP 
  FROM messages;

SELECT * FROM likes LIMIT 10; -- Проверим

CREATE TABLE posts (-- Создадим таблицу постов
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  community_id INT UNSIGNED,
  head VARCHAR(255),
  body TEXT NOT NULL,
  media_id INT UNSIGNED,
  is_public BOOLEAN DEFAULT TRUE,
  is_archived BOOLEAN DEFAULT FALSE,
  views_counter INT UNSIGNED DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- заполняем посты
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (1, 5, 6, 'omnis', 'Sequi dolor velit ut aut. Impedit atque dolore provident assumenda eaque. Ab natus tempore perferendis eos.', 4, 0, 1, 976951, '2006-02-11 17:08:35', '1998-10-06 07:50:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (2, 1, 7, 'magnam', 'Ducimus enim minima ipsam aut est. Labore nobis tenetur similique. Ut qui sed cupiditate quisquam error omnis.', 5, 1, 0, 31, '1991-10-03 00:40:05', '1982-12-17 01:14:29');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (3, 4, 6, 'doloribus', 'Et eos aut doloribus asperiores non tenetur quibusdam. Temporibus provident voluptas nisi corrupti molestias et. Et qui ea aut voluptas. Voluptatem quia doloremque ut qui error voluptatem nostrum sit.', 9, 1, 0, 7724, '2015-12-04 20:04:46', '1973-07-04 04:55:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (4, 0, 5, 'omnis', 'Odio in omnis saepe enim eos. Reprehenderit reprehenderit ut in. Quasi quis et porro nobis vel at incidunt.', 2, 0, 1, 3679, '1999-03-06 15:52:03', '2008-12-20 09:30:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (5, 4, 1, 'libero', 'Numquam ut quia nam eius repudiandae rerum ut. Expedita dignissimos enim rerum aut. Similique laudantium error quae.', 8, 0, 0, 12596821, '2010-03-28 20:24:44', '1990-06-15 19:56:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (6, 7, 5, 'et', 'Voluptatem sit explicabo illum amet quae dignissimos reprehenderit. Laborum blanditiis aut ex ipsam. Blanditiis deserunt magnam quam vel quia et.', 9, 1, 0, 1941969, '2011-12-26 22:14:28', '1996-11-11 22:32:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (7, 7, 3, 'hic', 'Consequuntur molestiae perspiciatis rerum iusto distinctio unde pariatur. Sint sunt nisi tempora voluptatem pariatur. Vel soluta aut sequi officia officiis. Et voluptatem eum officiis natus mollitia.', 3, 0, 0, 25167, '2003-06-03 22:50:25', '2012-07-22 13:11:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (8, 8, 4, 'vero', 'Sunt suscipit fugit aliquam molestiae commodi aliquid excepturi odio. Quod omnis repellendus qui ea et. Recusandae commodi accusamus in beatae veniam qui.', 3, 1, 0, 68614255, '2008-07-23 00:40:54', '2004-05-18 19:15:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (9, 9, 1, 'non', 'Perspiciatis dolorum neque iste consequatur et sit nulla a. Consequatur numquam amet sapiente. Necessitatibus vitae occaecati voluptatum placeat. Nulla omnis voluptas consequatur.', 0, 1, 0, 44, '1984-03-25 06:04:00', '2010-08-06 14:30:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (10, 6, 5, 'porro', 'Ex voluptatem itaque quos rerum. Et quia voluptatum ut rerum molestias voluptatem illum aut. Modi quam et ut. Sunt cupiditate dolores consequatur labore et.', 9, 0, 1, 79, '1998-07-15 10:45:07', '2014-11-07 22:37:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (11, 8, 7, 'natus', 'Quam blanditiis fugiat aut veritatis velit. Earum laborum vel laborum expedita. Fugiat est officia cum culpa. Similique labore quo consectetur dolorem velit.', 0, 0, 0, 94955542, '1984-03-03 09:39:39', '2006-06-26 11:18:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (12, 5, 6, 'rerum', 'Rerum sit odit numquam corporis sed quis. Consequatur qui non est et rerum illum aut fugiat. Rerum quod nostrum enim et.', 8, 1, 1, 577, '2016-11-10 02:40:30', '1974-05-17 04:50:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (13, 3, 5, 'modi', 'Et alias deleniti pariatur ratione voluptas aut. Nisi praesentium sit exercitationem. Libero placeat rerum dolorum quasi et perspiciatis. Voluptatum ut vel provident quis quo numquam. Optio error rerum iste sequi.', 8, 0, 1, 880, '1993-06-17 11:22:07', '1979-02-20 20:56:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (14, 1, 5, 'culpa', 'Sed odit assumenda ab tempore odit soluta. Et ab dolor tempora perspiciatis voluptatem. Tenetur aut et dolorum deserunt.', 0, 1, 1, 50170077, '2014-06-24 09:01:59', '2008-09-07 04:13:02');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (15, 8, 3, 'aut', 'Ea alias explicabo tempore eum. Asperiores temporibus cumque ut totam minus fugiat dicta. Odit aut enim provident molestiae id doloribus fugit.', 5, 0, 1, 906, '1988-05-02 04:28:15', '1984-10-09 14:21:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (16, 6, 0, 'nihil', 'Tempore sapiente porro expedita praesentium voluptatem. Itaque ipsum neque autem voluptatibus. Optio voluptas quam nihil iste velit id. Officia quis perferendis et sed eligendi.', 6, 1, 1, 4133309, '2007-03-05 19:51:06', '1972-12-24 21:52:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (17, 6, 9, 'vitae', 'Quo ipsum consequatur et ea. Alias at illum voluptatem saepe aliquam nostrum facilis. Aut enim doloribus natus eos nam. Commodi earum esse est quod sunt.', 8, 1, 1, 6441, '2012-07-26 06:54:27', '2015-06-27 20:55:40');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (18, 5, 9, 'officiis', 'Sed sit aspernatur voluptas quo similique. Totam eum neque aut alias error doloremque. Dolor odit perferendis dolore qui voluptate et.', 8, 0, 1, 543490, '1988-03-04 01:46:26', '1987-08-28 18:22:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (19, 6, 2, 'voluptatibus', 'Cumque harum unde eius optio aspernatur. Quas perspiciatis itaque aliquid vel perspiciatis modi officiis quaerat. Eum ad est praesentium consequatur ut animi et. Incidunt laboriosam facilis delectus quam.', 1, 0, 0, 82821, '1976-11-16 13:00:50', '2010-06-27 13:30:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (20, 1, 9, 'recusandae', 'Quis itaque aut dicta. Atque expedita dolor in est qui voluptatibus. Ea et ipsa ad est omnis vel. Deleniti aut eligendi itaque exercitationem et amet.', 7, 0, 0, 29210554, '2014-05-02 02:27:38', '2015-12-05 11:26:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (21, 5, 7, 'ea', 'Temporibus fuga provident laboriosam non. Quod vitae modi qui sunt hic. Nisi nisi voluptas nihil optio voluptates voluptatibus. Perspiciatis earum animi molestiae non odio ipsa ab culpa.', 6, 1, 1, 20658978, '1997-10-04 13:04:55', '2015-03-25 18:25:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (22, 8, 4, 'adipisci', 'Autem et nam iure omnis consequatur placeat. Dignissimos ut nobis dolores. Assumenda voluptatum et eos rerum quia iure vero. Qui harum labore quia optio nihil.', 6, 1, 1, 43635083, '2010-06-02 03:19:56', '1995-08-21 08:45:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (23, 3, 9, 'maiores', 'Sequi beatae blanditiis saepe non aut et rem. Quibusdam exercitationem et hic quod. Rerum et nesciunt minima sit non ipsum aut debitis. Et deleniti facere distinctio non.', 3, 1, 0, 17, '1996-08-03 18:32:28', '1992-01-18 11:56:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (24, 7, 7, 'in', 'Odio deserunt aspernatur soluta laudantium reiciendis ea. Et praesentium eum aut praesentium. Fugit impedit repellat aut minus.', 4, 0, 1, 558307, '1978-03-03 18:41:16', '1988-07-29 10:17:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (25, 5, 0, 'quos', 'Optio voluptas voluptatem incidunt id assumenda earum ex. Ad nihil animi consectetur et labore. Ullam deserunt qui sed velit rerum ut.', 7, 0, 1, 232671809, '1979-03-13 04:48:47', '1985-08-07 07:45:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (26, 6, 4, 'tenetur', 'Quae nesciunt dolor est rerum molestias quae. Dolor soluta quis ut nesciunt. Voluptas ut ut sint qui necessitatibus perferendis velit.', 1, 0, 1, 0, '2005-04-16 20:56:46', '2006-04-11 01:35:21');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (27, 4, 4, 'odio', 'Eos rerum officiis incidunt ratione. Molestiae et aliquam unde. Eum exercitationem sit odit consequatur et assumenda aspernatur. Molestiae recusandae odit et et.', 6, 0, 0, 671, '2016-09-19 19:34:49', '2006-08-24 17:33:53');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (28, 7, 2, 'sed', 'Voluptas eos blanditiis incidunt architecto. Enim et molestiae occaecati dignissimos. Deleniti sit debitis voluptatem officia accusamus omnis et. Natus dolorum commodi rerum quas aut. Sunt et quia ut qui doloremque repellat.', 8, 1, 0, 4837, '1975-01-29 00:01:21', '2018-12-29 15:50:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (29, 4, 8, 'veniam', 'Adipisci ipsa eum suscipit quidem est et. Adipisci sit occaecati quas ut temporibus quia dolorem. Aliquam enim ipsa ut qui explicabo et esse. Hic est atque sequi sequi ut.', 8, 1, 0, 4993882, '1974-01-27 00:48:06', '1997-03-27 07:26:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (30, 4, 2, 'error', 'Saepe facilis quis rerum. Officiis et accusantium odit voluptatum. Enim assumenda et est reiciendis quisquam. Dolorum consectetur maiores tempore aut est.', 4, 1, 0, 1, '2001-10-27 21:26:00', '1984-12-11 06:56:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (31, 1, 3, 'id', 'Deserunt sint voluptas beatae quia odit. Harum quo quos totam. Vitae alias corporis suscipit et.', 6, 1, 1, 5, '1996-11-18 11:26:05', '1978-09-09 13:27:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (32, 7, 7, 'voluptatem', 'Minima deleniti ea quos. Doloremque ut quisquam minima molestias.', 5, 0, 1, 6014, '1975-03-26 02:38:34', '2007-04-04 04:53:50');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (33, 3, 6, 'similique', 'Repudiandae dolor alias non in quia. Est odit mollitia unde dolore delectus aspernatur. Quo velit sint reiciendis aperiam explicabo assumenda. Quia sunt quo sit tempora omnis aut nam sit.', 8, 0, 1, 423084, '2007-06-04 03:04:56', '2007-08-23 12:27:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (34, 7, 8, 'repellendus', 'Veniam quis molestias incidunt neque molestias. Aut non aut ad non ut. Consequatur aliquid dolor deserunt possimus.', 7, 0, 1, 32763, '2020-03-02 16:13:13', '1981-07-16 15:14:38');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (35, 8, 4, 'voluptatum', 'Sunt cum architecto aut nemo. Molestias ullam hic dolore quis reiciendis dolore. Suscipit tempora suscipit maiores hic debitis soluta dolorem qui.', 5, 0, 1, 7954278, '2019-01-24 17:48:05', '1991-02-06 23:44:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (36, 7, 9, 'porro', 'Voluptate sequi magni rerum. Est non omnis deserunt ab hic dolores consequatur. Quia cum sunt cumque repellat et.', 6, 0, 0, 86937, '1994-09-24 05:37:08', '1998-09-24 18:52:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (37, 7, 3, 'dolores', 'Culpa eum inventore distinctio consectetur nam consequuntur voluptatem esse. Delectus magni distinctio vel facilis. Quaerat at est unde in. Autem placeat maxime quae sit ea.', 7, 1, 0, 6375268, '1974-08-24 01:41:53', '1990-07-09 07:58:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (38, 0, 9, 'quaerat', 'Nihil nostrum fugiat repudiandae eligendi fuga magni aut. Et ducimus qui dolor consectetur qui. Animi mollitia quia magnam laborum aut. Aut reiciendis facilis aut distinctio asperiores cumque. Illo eveniet voluptatem pariatur ut aut in voluptate quod.', 4, 0, 0, 621781390, '2003-03-07 03:42:10', '2017-07-01 21:49:14');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (39, 3, 9, 'qui', 'Amet velit voluptates non et in sed. Deleniti ullam cupiditate ut repellat. Cupiditate reiciendis sint consequatur illo sunt debitis.', 8, 1, 1, 540, '1984-06-29 07:37:37', '2014-12-07 17:08:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (40, 9, 7, 'quo', 'Maiores itaque fuga asperiores ab. Labore quas porro necessitatibus et quisquam ut porro. Quo aut quidem quisquam culpa natus mollitia numquam. Aperiam qui dolorem commodi est.', 7, 0, 1, 786, '2011-11-14 22:39:26', '1970-08-11 15:15:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (41, 5, 8, 'alias', 'Sit aut in exercitationem sit facilis perferendis sapiente. Omnis doloremque molestiae dolores qui fugit error. Nulla reiciendis et ea eveniet ipsum et harum.', 7, 0, 0, 9359102, '2003-03-06 18:30:32', '1993-02-16 02:17:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (42, 8, 8, 'exercitationem', 'Molestiae saepe ducimus consequuntur libero aut. Atque quia enim velit similique praesentium. Sit neque quis recusandae ducimus non ut.', 2, 1, 0, 0, '1992-03-04 18:47:43', '1982-04-02 15:25:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (43, 8, 6, 'odit', 'Nesciunt enim et quisquam est. Sed ducimus itaque amet atque. Perferendis sed libero dicta ut dolores dolor. Numquam placeat est qui molestias ratione velit voluptas.', 8, 1, 0, 55, '1975-09-19 11:55:29', '2014-07-06 21:00:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (44, 6, 4, 'ullam', 'Voluptate non voluptatem aut ut rem quo molestiae. Dolorum adipisci eum excepturi accusamus. Porro suscipit fugit minima.', 7, 1, 1, 97875, '1988-07-25 23:17:56', '1977-09-11 08:48:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (45, 2, 5, 'et', 'Atque dolore aut similique voluptas voluptatem minus sed. Fuga suscipit inventore dignissimos. Voluptate velit sapiente quod ut.', 6, 1, 0, 3, '2019-06-22 18:49:21', '1986-09-28 12:18:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (46, 5, 5, 'exercitationem', 'Enim eum ratione molestiae explicabo aut voluptas. Ad aperiam et aut voluptatem. Dicta eaque ut saepe amet ratione qui culpa est. Sint dolorem repellendus voluptate sed laboriosam et quo.', 4, 0, 0, 945595, '1971-05-12 02:16:31', '1997-04-21 08:36:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (47, 6, 1, 'unde', 'Omnis ducimus ab nesciunt vero. Autem dolore ut possimus. Id nihil est voluptate optio sit.', 0, 0, 1, 562169, '1986-09-03 04:49:54', '1997-02-26 21:31:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (48, 1, 0, 'unde', 'Dolor quasi et ipsam rerum. Totam culpa qui veritatis itaque et. Dignissimos incidunt eum quas dignissimos dolores modi rerum. Provident numquam perferendis sapiente et ad unde.', 8, 1, 1, 45689916, '1979-07-28 09:09:07', '1972-07-24 05:16:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (49, 4, 6, 'excepturi', 'Unde necessitatibus ut neque dolor molestias sed. Nulla ut et asperiores. Sit ipsum et impedit voluptas.', 3, 0, 1, 770269, '2012-12-02 16:47:26', '1992-06-04 17:04:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (50, 0, 2, 'excepturi', 'Quo aliquid et officiis id assumenda itaque. Rerum voluptas minima commodi aspernatur. Delectus maiores voluptatum sunt aut.', 8, 0, 0, 11, '1989-11-05 00:30:04', '2020-04-11 11:22:02');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (51, 1, 8, 'nisi', 'Ipsum eum porro ab aliquam mollitia. Facere ut laudantium porro soluta vel doloremque aut.', 4, 0, 0, 442323818, '1976-10-02 13:59:11', '1974-02-14 19:39:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (52, 1, 4, 'sunt', 'Qui omnis facilis unde impedit. Ut vel aspernatur est dignissimos inventore voluptatum quis. Consequatur autem perspiciatis praesentium voluptatum. Architecto aut nesciunt qui accusamus.', 4, 0, 1, 33, '2012-05-12 18:28:37', '1996-11-19 21:57:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (53, 7, 8, 'qui', 'Facilis dolorem eligendi iure sunt ut. Eaque consequatur provident minima sapiente rem et et. Suscipit sed totam eligendi atque sed dolor.', 5, 1, 0, 6243, '1977-10-02 13:45:57', '1985-03-04 08:57:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (54, 9, 1, 'neque', 'Quo nisi ipsa sint voluptates odit temporibus sint. Sed sit quis vero rem incidunt.', 9, 0, 0, 334278, '1983-01-29 05:01:26', '2010-01-27 09:50:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (55, 8, 1, 'laborum', 'Accusamus excepturi facilis maxime quia eaque. Explicabo illum qui consectetur molestias labore. Tempora laboriosam adipisci aperiam qui qui incidunt. Occaecati laborum harum illum voluptatibus ullam ducimus porro.', 2, 1, 0, 3101101, '2000-11-28 20:24:51', '1999-09-12 08:36:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (56, 4, 6, 'explicabo', 'Praesentium neque et dolor. Nihil sapiente nulla consequuntur sit rerum. Est libero voluptatem voluptatem cumque voluptas ea mollitia iusto.', 4, 1, 0, 64793, '2012-02-06 12:38:38', '1984-02-08 03:02:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (57, 0, 2, 'atque', 'Sint rerum maxime sequi odit. Voluptatibus doloribus non quia illo accusantium ut et nihil. Quas modi voluptas aut quo. Quidem tenetur placeat voluptates.', 7, 1, 0, 4, '2002-06-02 19:37:01', '1992-06-05 04:25:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (58, 4, 6, 'atque', 'Sed consequatur repellendus vero. Esse a facere qui aliquam expedita. Facilis quia doloribus commodi. Vel dicta molestiae sit sed architecto laudantium omnis.', 5, 0, 0, 571261, '1986-11-30 02:19:36', '2004-05-09 21:45:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (59, 5, 7, 'facilis', 'Deleniti voluptatem qui ut ullam aut et. Totam et voluptatibus eveniet eum dolores.', 1, 0, 1, 2099, '1978-07-01 03:24:53', '1996-07-15 13:31:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (60, 1, 7, 'quasi', 'Delectus impedit neque explicabo ad quisquam. Molestias voluptas excepturi dolores culpa consequatur. Fuga ea doloremque sequi aut et eum animi. Velit consequatur perferendis quis est qui.', 4, 0, 1, 96, '2006-07-05 08:36:41', '2001-10-10 16:54:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (61, 3, 2, 'rem', 'Atque omnis sint non officia quam voluptas. Nemo mollitia autem labore sint explicabo sunt.', 7, 1, 1, 0, '1990-02-09 13:52:56', '1989-03-26 06:26:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (62, 1, 8, 'nihil', 'Ut molestias omnis repellat hic et. Et et qui aut qui sint. Et aut consequuntur recusandae ullam.', 7, 1, 0, 9292, '2007-06-09 10:59:00', '1998-09-10 04:21:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (63, 6, 1, 'nihil', 'Pariatur sunt et sed laborum sed voluptatum magnam. Sed adipisci et et ipsum quos. Eum officiis veniam voluptatem quia voluptatibus eveniet sed. Vitae iste aspernatur et ea.', 6, 0, 1, 4940023, '2015-05-04 19:07:02', '2001-02-20 16:43:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (64, 1, 1, 'optio', 'Veritatis alias itaque sit. Blanditiis natus quasi sed enim sit ipsa laboriosam. Mollitia praesentium eos et id eveniet inventore.', 4, 0, 0, 1225862, '1991-01-02 17:00:59', '2002-05-01 09:02:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (65, 4, 0, 'tempore', 'Sint facere nisi repudiandae aut quisquam soluta aut. Quia veniam praesentium architecto sapiente. Est non dicta sunt ex. Consequatur fuga voluptas cum officia.', 6, 0, 1, 38, '1976-08-05 01:07:16', '1998-08-20 06:55:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (66, 1, 7, 'voluptates', 'Quas temporibus repellat nesciunt blanditiis sit perspiciatis suscipit. Architecto non rem odit. Eaque incidunt reiciendis dolor repellendus sint.', 3, 0, 1, 489222375, '1971-03-16 14:12:44', '2002-08-31 15:41:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (67, 1, 0, 'dolor', 'Magni ducimus nemo est tenetur. Aspernatur autem ut quibusdam nesciunt. Aut veritatis aut quia fuga molestiae qui illo.', 5, 0, 0, 6945, '1977-09-27 23:27:04', '2015-02-15 08:41:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (68, 1, 0, 'illum', 'Blanditiis voluptas soluta nobis voluptates reiciendis debitis. Soluta nostrum qui quisquam voluptate. Quaerat non nostrum ut aut cum magni consequuntur.', 8, 1, 0, 5259, '1987-05-26 19:39:49', '1982-09-18 16:39:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (69, 5, 7, 'voluptatem', 'Architecto non voluptas nobis harum. Voluptas neque nobis delectus voluptas nam. Ea quia commodi amet itaque voluptatum laudantium error.', 5, 1, 0, 4012223, '2013-11-19 20:05:11', '1992-06-07 02:32:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (70, 8, 5, 'assumenda', 'Rem omnis voluptate qui et dignissimos. Ut vero aperiam qui voluptas tempora aut dolor enim.', 9, 0, 1, 4, '1994-02-26 18:07:14', '1990-10-18 22:10:50');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (71, 7, 9, 'ipsum', 'Cumque quasi nesciunt repellat excepturi. Delectus unde optio sapiente consequuntur voluptates atque et ratione.', 2, 1, 0, 6655, '1989-09-09 02:52:16', '2017-11-24 20:37:53');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (72, 7, 8, 'omnis', 'Qui praesentium maxime veniam cupiditate. Id earum autem facilis sunt non. Quod asperiores aut magnam.', 4, 1, 0, 58, '1972-12-11 03:45:38', '1984-07-09 22:35:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (73, 6, 9, 'eligendi', 'Animi ipsam occaecati adipisci ex. Non aut quae consequatur consequatur incidunt dolorem quis. Aut ut inventore cumque quia quis fugit ea.', 0, 0, 1, 224994, '2001-08-18 23:11:50', '1979-02-17 07:21:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (74, 4, 7, 'autem', 'Nostrum sit et eum rerum et magni. Neque alias et adipisci unde. Est illum suscipit ut quia temporibus nesciunt quia. Quia dolorum qui et est libero voluptatum. Alias quas omnis ipsam velit voluptas.', 5, 1, 1, 1000, '2014-06-21 20:38:27', '1986-10-02 00:59:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (75, 1, 8, 'iste', 'Ab dolor qui ratione. Illo natus neque nemo aspernatur dignissimos et. Esse et ea blanditiis atque neque voluptatibus est molestias. Voluptatem tempore dignissimos molestiae hic deleniti.', 8, 0, 1, 0, '2014-03-10 08:49:52', '1978-10-12 14:53:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (76, 2, 4, 'tenetur', 'Consectetur qui nemo corporis et dolores autem doloribus rerum. Aut ab quod voluptatibus placeat. Vel nostrum quis ratione eveniet qui commodi. Temporibus vel qui aliquid. Voluptatem quasi quia nesciunt quo.', 4, 0, 1, 6, '2015-11-17 17:52:40', '2018-03-05 15:52:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (77, 0, 1, 'sit', 'Nobis ut ut quibusdam nihil voluptatem consequuntur est. Non sint ullam autem aut qui. Soluta sint tenetur ab nobis tempore ea eligendi. Vel nostrum nemo voluptate et molestiae.', 7, 1, 1, 493476022, '1983-02-17 02:13:14', '2001-12-31 01:28:55');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (78, 1, 1, 'rerum', 'Excepturi architecto architecto aperiam et quia et. Officiis totam ut sed unde. Dolor harum asperiores tempora sit.', 2, 1, 1, 2235362, '1988-10-18 20:45:40', '2010-03-17 01:16:53');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (79, 3, 3, 'possimus', 'Voluptatem aut aut possimus ducimus libero quis voluptatem. Minus ut earum impedit adipisci doloremque vel dignissimos illum. Ex tempora saepe alias esse.', 6, 0, 0, 784146, '1983-05-01 02:12:34', '1978-05-16 12:38:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (80, 3, 5, 'fugiat', 'Saepe aut et quisquam quisquam. Sit sequi nam error blanditiis.', 6, 0, 1, 29073366, '1991-11-25 08:25:17', '2020-04-11 19:06:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (81, 5, 6, 'tempora', 'Quisquam iste earum facilis quod similique adipisci neque. Earum sed quaerat rerum reprehenderit temporibus aut harum eos. Rerum nesciunt et dolorem nihil similique laboriosam nesciunt eligendi.', 2, 0, 1, 31582564, '2006-01-24 15:37:29', '1977-03-27 11:29:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (82, 4, 4, 'soluta', 'Enim molestias et laborum. Et cupiditate ut expedita et. Voluptatum laborum est voluptatibus ea quibusdam tempore.', 2, 0, 1, 450408, '2010-07-07 04:57:22', '2009-04-20 23:03:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (83, 4, 6, 'corporis', 'Iste velit ipsa ut voluptatem non reiciendis. Debitis repellendus fuga voluptatibus possimus omnis sunt quia. Sequi fugit nobis exercitationem nulla sunt et. Et commodi quia eius eligendi necessitatibus explicabo.', 5, 1, 0, 0, '2000-07-29 22:43:50', '1995-07-21 08:21:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (84, 7, 8, 'culpa', 'Exercitationem facere dolorem rerum. Beatae dolores officiis in vel culpa amet dolores.', 4, 1, 1, 330787, '2014-09-27 21:14:36', '1999-05-26 07:25:10');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (85, 8, 8, 'rem', 'Dolorem perferendis soluta saepe rem harum inventore laboriosam. Labore est officiis itaque pariatur possimus ducimus. Ab id laudantium magnam nihil consectetur sed.', 9, 1, 0, 77449910, '1987-10-07 22:07:22', '1973-09-12 19:32:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (86, 7, 2, 'voluptatem', 'Eos dolore aut blanditiis. Nam a est impedit. Qui distinctio dolorem nam.', 8, 1, 0, 251, '1999-02-15 01:32:22', '1982-02-13 13:27:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (87, 9, 2, 'suscipit', 'Et nisi et et dolorum aut. Est itaque saepe veniam repellendus. Commodi quae dolorem incidunt ab.', 9, 1, 1, 58337636, '1990-02-21 11:32:48', '1980-05-03 22:00:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (88, 3, 7, 'sit', 'Exercitationem aut facere eaque. Sint consequuntur velit cupiditate enim pariatur reprehenderit.', 8, 1, 1, 13248859, '1999-04-14 14:53:13', '1994-06-09 14:32:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (89, 1, 3, 'quisquam', 'A nam consectetur in atque. Quam rerum rerum eum itaque tempore. Quibusdam aut non at non provident consequatur porro.', 7, 1, 1, 3, '2008-02-15 13:41:15', '2014-11-18 23:11:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (90, 5, 5, 'veniam', 'Minus iure nobis omnis expedita a. Necessitatibus iure nihil possimus cupiditate ipsa. Inventore aut iusto quae.', 7, 0, 0, 91213, '1983-06-19 00:25:54', '1970-10-23 05:53:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (91, 0, 0, 'et', 'Provident voluptatem explicabo id accusamus qui sint dolorum. Ut est laudantium non itaque dicta et. Ad necessitatibus necessitatibus veniam odio et qui rem quia.', 8, 1, 1, 587110, '2012-10-20 05:21:16', '2017-08-12 11:06:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (92, 0, 4, 'voluptas', 'Et laboriosam libero aut saepe sit. Et deleniti aut aut enim accusamus. Fugit est omnis et a ut culpa molestiae totam.', 1, 0, 1, 0, '1985-03-02 19:59:59', '1972-12-31 18:33:50');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (93, 3, 4, 'reiciendis', 'Ut amet necessitatibus omnis numquam nisi. Facere quia doloremque voluptatum atque voluptatem in. Eligendi placeat et mollitia est fugit.', 8, 1, 0, 8, '2007-09-23 20:15:47', '1978-01-26 14:25:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (94, 6, 6, 'commodi', 'Quod et sint est. Minima nemo facilis delectus dicta sapiente tempora aut.', 1, 0, 1, 2, '1977-11-22 12:16:55', '2008-11-23 17:28:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (95, 4, 8, 'qui', 'Nesciunt voluptatem est in iure. Minus voluptas doloribus asperiores sed error aut. Voluptatem est excepturi eum vel neque. Voluptatem sit ut eos dolor.', 0, 0, 1, 78955, '1986-12-10 20:02:43', '1978-11-10 00:12:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (96, 8, 2, 'ipsam', 'Tempore quia quo blanditiis. Aut velit non quia dicta. Est et labore debitis amet voluptatem aliquid. Molestiae asperiores sequi aut.', 1, 1, 1, 1860331, '1987-06-12 10:58:26', '1993-04-26 12:56:29');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (97, 0, 4, 'dicta', 'Aliquam pariatur quae reiciendis nihil neque nemo dicta. Cumque qui aliquid aut consequatur et provident ut sint. Quae placeat cupiditate nam harum. Illo nemo nam impedit sint.', 6, 1, 0, 0, '1982-07-31 05:02:41', '1971-02-05 06:46:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (98, 4, 3, 'a', 'Optio nam et eius non quis. Voluptate id rerum veniam. Ut laudantium non deleniti dolore qui optio. Dolorem ut labore consequatur dolorem.', 1, 0, 1, 5520305, '1994-04-07 22:59:16', '2020-05-08 13:02:55');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (99, 8, 3, 'natus', 'Aut eius aut provident dolorem. Reiciendis id quidem eum numquam cupiditate maxime vero nulla. Nihil eos laborum ut cumque velit eum vel. Rerum consequatur fugiat iusto eum perspiciatis maiores suscipit.', 9, 0, 0, 0, '2000-07-10 07:57:20', '1998-01-25 09:49:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (100, 1, 5, 'qui', 'Sit consequuntur ab perferendis eaque ea. Perferendis eum est eius numquam necessitatibus. Id deleniti voluptates aut suscipit repudiandae id facere.', 0, 1, 1, 54, '2013-05-30 12:23:32', '1992-11-28 05:42:14');

UPDATE posts SET updated_at = NOW();








